import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Auth from "~/components/Auth";
import CreatePostWizard from "~/components/CreatePostWizard";
import Feed from "~/components/Feed";

const Home: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <Auth />
        <div className="w-full h-full md:max-w-2xl border-x border-slate-400">
          <CreatePostWizard />
          <Feed />
        </div>
      </main>
    </>
)};

export default Home;
