import { type NextPage } from "next";
import Head from "next/head";
import Auth from "~/components/Auth";
import CreatePostWizard from "~/components/CreatePostWizard";
import PostView from "~/components/PostView";

import { api, } from "~/utils/api";

const Home: NextPage = () => {

  const {data, isLoading} =  api.post.getAll.useQuery();
  
  if (isLoading) return <div>Loading ...</div>
  if (!data) return <div>Woops no data</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <Auth />
        <div className="w-full h-full md:max-w-2xl border-x border-slate-400">
          <CreatePostWizard />
          <div className="flex flex-col">
            {data?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id}/>
              ))}
          </div>  
        </div>
      </main>
    </>
)};

export default Home;
